Update to version 1.0.2
* - Made the back-to-top button translatable & updated translation files.
* - Fixed: "Uncaught TypeError: $container.isotope is not a function".
* - Changed theme URI to: https://michaelvandenberg.com/themes/#magnum-opus